name: Build and Test Spring Boot Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'planet'
          mysql root password: 'rootpass'
          mysql user: 'root'
          mysql password: ''

      - name: Wait for MySQL to be ready
        run: |
          sudo apt-get install -y netcat
          while ! nc -z localhost 3306; do   
            echo "Waiting for MySQL...";
            sleep 5;
          done;
          echo "MySQL is up and running"

      - name: Build with Maven
        run: mvn clean install