name: Lighthouse

on:
  push:
    branches:
      - pipeline

jobs:
  lighthouse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'planet'
          mysql root password: 'roott'
          mysql user: 'root'
          mysql password: 'roott'

      - name: Start Spring PlanetExpress
        run: mvn spring-boot:run
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/planet
          SPRING_DATASOURCE_USERNAME: root
          SPRING_DATASOURCE_PASSWORD: 'roott'


#name: Lighthouse
#
#on:
#  push:
#    branches:
#      - pipeline
#
#jobs:
#  lighthouse:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'temurin'
#          java-version: '17'
#
#      - name: Build with Maven
#        run: mvn clean install
#
#      - name: Setup MySQL
#        uses: mirromutth/mysql-action@v1.1
#        with:
#          mysql database: 'planet'
#          mysql root password: 'roott'
#          mysql user: 'root'
#          mysql password: 'roott'
#
#
#      - name: Wait for MySQL to be ready
#        run: |
#          sudo apt-get install -y netcat
#          while ! nc -z localhost 3306; do
#            echo "Waiting for MySQL..."
#            sleep 5
#          done
#          echo "MySQL is up and running"
#
#      - name: Start Spring PlanetExpress
#        run: mvn spring-boot:run
#        env:
#          SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/planet
#          SPRING_DATASOURCE_USERNAME: root
#          SPRING_DATASOURCE_PASSWORD: 'roott'
#
#      - name: Verify Application is Running
#        run: |
#          sleep 30
#          curl --fail http://localhost:8080 || exit 1
#
#      - name: Install Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '18'
#
#      - name: Install Lighthouse
#        run: npm install -g lighthouse
#
#      - name: Run Lighthouse
#        run: |
#          sleep 10
#          npx lighthouse http://localhost:8080 --output json --output-path ./lighthouse-report.json
#
#      - name: List Generated Files
#        run: ls -la ./lighthouse-report.json
#
#      - name: Upload Lighthouse Report
#        uses: actions/upload-artifact@v2
#        with:
#          name: lighthouse-report
#          path: ./lighthouse-report.json
